[CORE-1135] Initial commit.
BookingBug/generator-bookingbug pull request #31
Opened 2016-12-21 18:17 UTC by WesleyPumpkinhead

This is a work in progress. Please do not merge.

2017-01-11 17:17 UTC, damianpudlo commented on app/index.js
> +                publicBookingOptions.map(function(option){
it's misuse of map function, could be replaced with simple for  loop

```
for(var optionKey in publicBookingOptions){
      var option  = publicBookingOptions[optionKey];

      ....
      ....                 
}
```

2017-01-11 17:17 UTC, damianpudlo commented on app/index.js
> +        _getPublicBookingOptions: function () {
function name is misleading - seems to be returning all available options but it returns selected one options

could we change it to _getSelectedPublicBookingOptions

2017-01-11 17:17 UTC, damianpudlo commented on app/index.js
> +                    }
we should terminate generation process if user tried to use non existing public booking option e.g.

```
if(index === -1){
   _this.log(errorLogFormat('possible possible public booking options'), optionsAbbreviations);
   process.exit(1);
}

options[index] = option
```

2017-01-11 17:17 UTC, damianpudlo commented on app/index.js
> +                if (response.googleMapsKey) this.googleMapsKey = response.googleMapsKey === "optional"? this._getOptionDefaults()['google-maps-key'] : response.googleMapsKey
missing comma

2017-01-11 17:17 UTC, damianpudlo commented on app/index.js
> +            this.log(typeof path.join, this.sourceRoot(),  this.type);
please remove log

2017-01-12 12:13 UTC, WesleyPumpkinhead commented on app/index.js
> +                publicBookingOptions.map(function(option){
you added that in, not me =D

2017-01-12 16:35 UTC, edclements requested changes
Can this be documented in the readme?

2017-01-13 12:01 UTC, damianpudlo approved these changes

2017-01-13 13:15 UTC, merged