[CORE-1399] [CORE-1400] Confirm staging/prod deploy and commit deploy version bump
BookingBug/generator-bookingbug pull request #40
Opened 2017-03-24 10:54 UTC by tomlandia

2017-04-27 12:08 UTC, damianpudlo requested changes

2017-04-27 12:08 UTC, damianpudlo commented on app/templates/gulp-tasks/tasks-register/bb-dev/confirm-deploy.js
> +                readline.question(question, function (answer) {
we should use inquirer instead of readline (see example in sdk: gulp-tasks/tasks-config/changelog.js)

2017-04-27 12:08 UTC, damianpudlo commented on app/templates/gulp-tasks/tasks-register/bb-dev/confirm-deploy.js
> +            if(configuration.environment.startsWith('dev')) {
please remove this if statement - let's do for all envs

2017-04-27 12:08 UTC, damianpudlo commented on app/templates/gulp-tasks/tasks-config/bb-dev/version.js
> +                    gulp.src(['./package.json'])
I belive it should be config.json, not package.json

2017-05-02 14:08 UTC, DeanPalmer commented
Made those changes @damianpudlo. Was wondering if inquirer should be a constant, if so I'll update.

2017-05-11 08:46 UTC, damianpudlo approved these changes

2017-05-11 09:14 UTC, merged