run gulp with --secure flag to start an https local webserver
BookingBug/generator-bookingbug pull request #46
Opened 2017-05-23 15:20 UTC by flaviotulino

2017-05-23 15:55 UTC, jthomas1 requested changes
You've overridden the regular config options with the test project config so just need to revert some things back to how they were

2017-05-23 15:55 UTC, jthomas1 commented on app/templates/gulp-tasks/tasks-config/common/webserver.js
> +        gulp.task('sdk-test-project:webserver', webServerTask);
remove `sdk-test-project:`

2017-05-23 15:55 UTC, jthomas1 commented on app/templates/gulp-tasks/tasks-config/common/webserver.js
> +                root: [configuration.testProjectReleasePath],
revert to: `[configuration.projectReleasePath]`

2017-05-23 15:55 UTC, jthomas1 commented on app/templates/gulp-tasks/tasks-config/common/webserver.js
> +                port: 8000,
revert to: `configuration.projectConfig.build.server_port`

2017-05-23 15:55 UTC, jthomas1 commented on app/templates/gulp-tasks/tasks-config/common/webserver.js
> +                uri: protocol + '://localhost:' + configuration.testProjectConfig.server_port + configuration.testProjectConfig.default_html
revert both instances of `testProjectConfig` to: `projectConfig.build`

2017-05-23 15:55 UTC, jthomas1 commented on app/templates/gulp-tasks/tasks-config/common/webserver.js
> +}).call(this);
Don't need `.call(this)`

2017-05-23 16:30 UTC, jthomas1 commented on app/templates/gulp-tasks/tasks-config/common/webserver.js
> +            const protocol = (args.secure !== null && args.secure !== undefined) ? 'https' : 'http';
this can be simplified to `args.secure ? 'https' : 'http'` as null and undefined are both falsy

2017-05-23 16:40 UTC, flaviotulino commented on app/templates/gulp-tasks/tasks-config/common/webserver.js
> +            const protocol = (args.secure !== null && args.secure !== undefined) ? 'https' : 'http';
well, I was not considering gulp --secure=hello as valid command; but technically, I agree.

2017-05-24 09:45 UTC, jthomas1 approved these changes

2017-05-24 09:46 UTC, merged